routes/admin.php
<?php

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------
|
| Here is where you can register Admin routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| is assigned the "admin" middleware group. Enjoy building your Admin!
|
*/

Route::get('dashboard', 'DashboardController@index')->name('dashboard');

Route::resource('users', 'UserController');

Route::resource('companies', 'CompanyController');

Route::resource('departments', 'DepartmentController');

Route::resource('employees', 'EmployeeController');

Route::resource('activitylogs', 'ActivityLogsController')->only(['index']);

routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['verify' => true]);

Route::get('/home', 'HomeController@index')->name('home')->middleware('verified');

Route::get('/', function() {
    return view('welcome');
});

app/Models/User.php
<?php

namespace App\Models;

use App\Mode\Point;
use App\Models\Restaurant;
use Laravel\Passport\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;
use Illuminate\Notifications\Notifiable;
use Spatie\Activitylog\Traits\LogsActivity;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Askedio\SoftCascade\Traits\SoftCascadeTrait;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable implements MustVerifyEmail
{
    use HasApiTokens, Notifiable, HasRoles, SoftDeletes, LogsActivity, SoftCascadeTrait;

    private const superAdmin = 'superadmin';

    protected $table = 'users';

    /**
     * The attributes that should be mutated to dates.
     *
     * @var array
     */
    protected $dates = ['deleted_at'];

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'uuid', 'email', 'email_verified_at', 'password', 'phone', 'address'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    public function getRouteKeyName()
    {
        return 'uuid';
    }

    public function point()
    {
        return $this->hasOne(Point::class);
    }

    public function scopeUuid($query, $uuid)
    {
        return $query->where('id', $uuid);
    }

    public function isSuperAdmin()
    {
        return $this->group == User::superAdmin;
    }

    public function getDescriptionForEvent($eventName)
    {
        $reflect = new \ReflectionClass($this);
        return $reflect->getShortName() . " - {$this->name} has been {$eventName}.";
    }
}

app/Http/Controllers/Backend/ActivityLogsController.php
<?php

namespace App\Http\Controllers\Backend;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Activitylog\Models\Activity;
use App\Http\Responses\ActivityLogsIndexResponse;

class ActivityLogsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $activitylogs = Activity::all();

        return new ActivityLogsIndexResponse($activitylogs);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }
}

app/Http/Controllers/Backend/CompanyController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Company;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Responses\CompanyIndexResponse;
use App\Http\Requests\Company\CreateCompanyRequest;
use App\Http\Requests\Company\UpdateCompanyRequest;

class CompanyController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $companies = Company::all();

        return new CompanyIndexResponse($companies);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.companies.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateCompanyRequest $request)
    {
        $request->storeCompany();

        flash('Company added!')->success()->important();

        return redirect()->route('backend.companies.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function show(Company $company)
    {
        return view('backend.companies.show', compact('company'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function edit(Company $company)
    {
        return view('backend.companies.edit', compact('company'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateCompanyRequest $request, Company $company)
    {
        $request->updateCompany($company);

        flash('Company updated!')->success()->important();

        return redirect()->route('backend.companies.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Company  $company
     * @return \Illuminate\Http\Response
     */
    public function destroy(Company $company)
    {
        $company->delete();

        if (request()->ajax()) {
            return response()->json(['message' => 'success'], 200);
        }

        flash('Company deleted!')->error()->important();

        return redirect()->route('backend.companies.index');
    }
}

app/Http/Controllers/Backend/DashboardController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\User;
use App\Models\Company;
use App\Models\Employee;
use App\Models\Department;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class DashboardController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users       = User::all()->count();
        $companies   = Company::all()->count();
        $employees   = Employee::all()->count();
        $departments = Department::all()->count();

        return view('backend.dashboard', compact(['users', 'companies', 'employees', 'departments']));
    }
}

app/Http/Controllers/Backend/DepartmentController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Company;
use App\Models\Department;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Responses\DepartmentIndexResponse;
use App\Http\Requests\Department\CreateDepartmentRequest;
use App\Http\Requests\Department\UpdateDepartmentRequest;

class DepartmentController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $departments = Department::all();

        return new DepartmentIndexResponse($departments);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();

        return view('backend.departments.create', compact('companies'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateDepartmentRequest $request)
    {
        $request->storeDepartment();

        flash('Department added!')->success()->important();

        return redirect()->route('backend.departments.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function show(Department $department)
    {
        return view('backend.departments.show', compact('department'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function edit(Department $department)
    {
        $companies = Company::all();

        return view('backend.departments.edit', compact(['department', 'companies']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateDepartmentRequest $request, Department $department)
    {
        $request->updateDepartment($department);

        flash('Department updated!')->success()->important();

        return redirect()->route('backend.departments.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Department  $department
     * @return \Illuminate\Http\Response
     */
    public function destroy(Department $department)
    {
        $department->delete();

        if (request()->ajax()) {
            return response()->json(['message' => 'success'], 200);
        }

        flash('Department deleted!')->error()->important();

        return redirect()->route('backend.departments.index');
    }
}

app/Http/Controllers/Backend/EmployeeController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\Company;
use App\Models\Employee;
use App\Models\Department;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Responses\EmployeeIndexResponse;
use App\Http\Requests\Employee\CreateEmployeeRequest;
use App\Http\Requests\Employee\UpdateEmployeeRequest;

class EmployeeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $employees = Employee::all();

        return new EmployeeIndexResponse($employees);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $companies = Company::all();
        $departments  = Department::all();

        return view('backend.employees.create', compact(['companies', 'departments']));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateEmployeeRequest $request)
    {
        $request->storeEmployee();

        flash('Employee added!')->success()->important();

        return redirect()->route('backend.employees.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function show(Employee $employee)
    {
        return view('backend.employees.show', compact('employee'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function edit(Employee $employee)
    {
        $companies = Company::all();
        $departments  = Department::all();

        return view('backend.employees.edit', compact(['employee', 'companies', 'departments']));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateEmployeeRequest $request, Employee $employee)
    {
        $request->updateEmployee($employee);

        flash('Employee updated!')->success()->important();

        return redirect()->route('backend.employees.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Employee  $employee
     * @return \Illuminate\Http\Response
     */
    public function destroy(Employee $employee)
    {
        $employee->delete();

        if (request()->ajax()) {
            return response()->json(['message' => 'success'], 200);
        }

        flash('Employee deleted!')->error()->important();

        return redirect()->route('backend.employees.index');
    }
}

app/Http/Controllers/Backend/UserController.php
<?php

namespace App\Http\Controllers\Backend;

use App\Models\User;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Http\Responses\UserIndexResponse;
use App\Http\Requests\User\CreateUserRequest;
use App\Http\Requests\User\UpdateUserRequest;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $users = User::all();

        return new UserIndexResponse($users);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.users.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreateUserRequest $request)
    {
        $request->storeUser();

        flash('User added!')->success()->important();

        return redirect()->route('backend.users.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function show(User $user)
    {
        return view('backend.users.show', compact('user'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function edit(User $user)
    {
        return view('backend.users.edit', compact('user'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function update(UpdateUserRequest $request, User $user)
    {
        $request->UpdateUser($user);

        flash('User updated!')->success()->important();

        return redirect()->route('backend.users.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\User  $user
     * @return \Illuminate\Http\Response
     */
    public function destroy(User $user)
    {
        $user->delete();

        if (request()->ajax()) {
            return response()->json(['message' => 'success'], 200);
        }

        flash('User deleted!')->error()->important();

        return redirect()->route('backend.users.index');
    }
}

resources/views/backend/users/create.blade.php
@extends('layouts.master')

@section('title', 'Create User')

@section('content')
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{{ route('backend.dashboard') }}">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{ route('backend.users.index') }}">Users</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>New</span>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h1 class="page-title"> User
    <small>management</small>
</h1>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <div class="boxless tabbable-reversed">
            <div class="tab-content">
                <div class="tab-pane active" id="tab_0">
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-users"></i>Create User</div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse"> </a>
                                <a href="#portlet-config" data-toggle="modal" class="config"> </a>
                                <a href="javascript:;" class="reload"> </a>
                                <a href="javascript:;" class="remove"> </a>
                            </div>
                        </div>
                        <div class="portlet-body form">
                            <!-- BEGIN FORM-->
                            <form action="{{ route('backend.users.store') }}" class="form-horizontal" method="POST">
                                @csrf
                                <div class="form-body">

                                    <div class="form-group{{ $errors->has('name') ? ' has-error ' : ''}}">
                                        <label for="name" class="col-md-3 control-label">Name</label>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" placeholder="Name"
                                            name="name" value="{{ old('name') }}" required>
                                            @if ($errors->has('name'))
                                                <span class="help-block"> {{ $errors->first('name') }} </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('email') ? ' has-error ' : ''}}">
                                        <label for="email" class="col-md-3 control-label">Email Address</label>
                                        <div class="col-md-4">
                                            <input type="email" class="form-control" placeholder="Email Address"
                                            name="email" value="{{ old('email') }}" required>
                                            @if ($errors->has('email'))
                                            <span class="help-block"> {{ $errors->first('email') }} </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('phone') ? ' has-error ' : ''}}">
                                        <label for="phone" class="col-md-3 control-label">Phone Number</label>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" placeholder="Phone Number"
                                            name="phone" value="{{ old('phone') }}" required>
                                            @if ($errors->has('phone'))
                                                <span class="help-block"> {{ $errors->first('phone') }} </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('address') ? ' has-error ' : ''}}">
                                        <label for="address" class="col-md-3 control-label">Address</label>
                                        <div class="col-md-4">
                                            <input type="text" class="form-control" placeholder="Address"
                                            name="address" value="{{ old('address') }}" required>
                                            @if ($errors->has('address'))
                                                <span class="help-block"> {{ $errors->first('address') }} </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('password') ? ' has-error ' : ''}}">
                                        <label for="password" class="col-md-3 control-label">Password</label>
                                        <div class="col-md-4">
                                            <input type="password" class="form-control" placeholder="Password"
                                            name="password" value="{{ old('password') }}" required>
                                            @if ($errors->has('password'))
                                            <span class="help-block"> {{ $errors->first('password') }} </span>
                                            @endif
                                        </div>
                                    </div>

                                    <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error ' : ''}}">
                                        <label for="password_confirmation" class="col-md-3 control-label">
                                            Confirm Password
                                        </label>
                                        <div class="col-md-4">
                                            <input type="password" class="form-control" placeholder="Confirm Password"
                                            name="password_confirmation" value="{{ old('password_confirmation') }}" required>
                                            @if ($errors->has('password_confirmation'))
                                            <span class="help-block"> {{ $errors->first('password_confirmation') }} </span>
                                            @endif
                                        </div>
                                    </div>

                                </div>

                                <div class="form-actions">
                                    <div class="row">
                                        <div class="col-md-offset-3 col-md-4">
                                            <button type="submit" class="btn green">Submit</button>
                                            <a type="button" class="btn default" href="{{ route('backend.users.index') }}">Cancel</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <!-- END FORM-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/backend/users/edit.blade.php
@extends('layouts.master')

@section('title', 'Edit User')

@section('content')
<div class="page-bar">
    <ul class="page-breadcrumb">
        <li>
            <a href="{{ route('backend.dashboard') }}">Home</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <a href="{{ route('backend.users.index') }}">Users</a>
            <i class="fa fa-angle-right"></i>
        </li>
        <li>
            <span>Edit</span>
        </li>
    </ul>
</div>
<!-- END PAGE BAR -->
<!-- BEGIN PAGE TITLE-->
<h1 class="page-title"> User
    <small>management</small>
</h1>
<!-- END PAGE TITLE-->
<!-- END PAGE HEADER-->
<div class="row">
    <div class="col-md-12">
        <div class="boxless tabbable-reversed">
            <div class="tab-content">
                <div class="tab-pane active" id="tab_0">
                    <div class="portlet box green">
                        <div class="portlet-title">
                            <div class="caption">
                                <i class="fa fa-users"></i>Edit User </div>
                            <div class="tools">
                                <a href="javascript:;" class="collapse"> </a>
                                <a href="#portlet-config" data-toggle="modal" class="config"> </a>
                                <a href="javascript:;" class="reload"> </a>
                                <a href="javascript:;" class="remove"> </a>
                            </div>
                        </div>
                        <div class="portlet-body form">
                            <!-- BEGIN FORM-->
                            <form action="{{ route('backend.users.update', $user->uuid) }}" class="form-horizontal" method="POST">
                                {{ method_field('PUT') }}
                                @csrf
                                <div class="form-body">
                                    <div class="form-group{{ $errors->has('name') ? ' has-error ' : ''}}">
                                            <label for="name" class="col-md-3 control-label">Name</label>
                                            <div class="col-md-4">
                                                <input type="text" class="form-control" placeholder="Name"
                                                name="name" value="{{ old('name') ? old('name') : $user->name }}" required>
                                                @if ($errors->has('name'))
                                                    <span class="help-block"> {{ $errors->first('name') }} </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group{{ $errors->has('email') ? ' has-error ' : ''}}">
                                            <label for="email" class="col-md-3 control-label">Email Address</label>
                                            <div class="col-md-4">
                                                <input type="email" class="form-control" placeholder="Email Address"
                                                name="email" value="{{ old('email') ? old('email') : $user->email }}" required>
                                                @if ($errors->has('email'))
                                                <span class="help-block"> {{ $errors->first('email') }} </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group{{ $errors->has('phone') ? ' has-error ' : ''}}">
                                            <label for="phone" class="col-md-3 control-label">Phone Number</label>
                                            <div class="col-md-4">
                                                <input type="text" class="form-control" placeholder="Phone Number"
                                                name="phone" value="{{ old('phone') ? old('phone') : $user->phone }}">
                                                @if ($errors->has('phone'))
                                                    <span class="help-block"> {{ $errors->first('phone') }} </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group{{ $errors->has('address') ? ' has-error ' : ''}}">
                                            <label for="address" class="col-md-3 control-label">Address</label>
                                            <div class="col-md-4">
                                                <input type="text" class="form-control" placeholder="Address"
                                                name="address" value="{{ old('address') ? old('address') : $user->address }}">
                                                @if ($errors->has('address'))
                                                    <span class="help-block"> {{ $errors->first('address') }} </span>
                                                @endif
                                            </div>
                                        </div>

                                        {{--  <div class="form-group{{ $errors->has('password') ? ' has-error ' : ''}}">
                                            <label for="password" class="col-md-3 control-label">Password</label>
                                            <div class="col-md-4">
                                                <input type="password" class="form-control" placeholder="Password"
                                                name="password" value="{{ old('password') }}">
                                                @if ($errors->has('password'))
                                                <span class="help-block"> {{ $errors->first('password') }} </span>
                                                @endif
                                            </div>
                                        </div>

                                        <div class="form-group{{ $errors->has('password_confirmation') ? ' has-error ' : ''}}">
                                            <label for="password_confirmation" class="col-md-3 control-label">
                                                Confirm Password
                                            </label>
                                            <div class="col-md-4">
                                                <input type="password" class="form-control" placeholder="Confirm Password"
                                                name="password_confirmation" value="{{ old('password_confirmation') }}">
                                                @if ($errors->has('password_confirmation'))
                                                <span class="help-block"> {{ $errors->first('password_confirmation') }} </span>
                                                @endif
                                            </div>
                                        </div>  --}}
                                </div>

                                <div class="form-actions">
                                    <div class="row">
                                        <div class="col-md-offset-3 col-md-4">
                                            <button type="submit" class="btn green">Submit</button>
                                            <a type="button" class="btn default" href="{{ route('backend.users.index') }}">Cancel</a>
                                        </div>
                                    </div>
                                </div>
                            </form>
                            <!-- END FORM-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection